import { Router, type IRouter } from "express";

const router: IRouter = Router();

const CERTIFICATIONS = [
  {
    id: "az-900",
    code: "AZ-900",
    name: "Azure Fundamentals",
    description: "Prove your foundational knowledge of cloud concepts and Azure services. Ideal for beginners and non-technical roles.",
    level: "Fundamentals",
    iconColor: "#0078d4",
    topicAreas: [
      "Cloud Concepts",
      "Azure Architecture",
      "Azure Services",
      "Azure Management Tools",
      "Azure Security",
      "Privacy & Compliance",
      "Pricing & Support",
    ],
  },
  {
    id: "az-104",
    code: "AZ-104",
    name: "Azure Administrator",
    description: "Demonstrate your skills in implementing, managing, and monitoring Azure environments for enterprises.",
    level: "Associate",
    iconColor: "#107c10",
    topicAreas: [
      "Identity & Governance",
      "Storage",
      "Compute Resources",
      "Virtual Networking",
      "Monitoring & Backup",
    ],
  },
  {
    id: "az-204",
    code: "AZ-204",
    name: "Azure Developer",
    description: "Demonstrate your ability to design, build, test, and maintain cloud applications and services on Microsoft Azure.",
    level: "Associate",
    iconColor: "#107c10",
    topicAreas: [
      "Azure Compute Solutions",
      "Azure Storage",
      "Azure Security",
      "Azure Monitor & Logging",
      "Azure API Management",
      "Azure Event-Based Solutions",
      "Azure Message-Based Solutions",
    ],
  },
  {
    id: "az-500",
    code: "AZ-500",
    name: "Azure Security Engineer",
    description: "Validate your skills in implementing security controls and threat protection, managing identity and access.",
    level: "Associate",
    iconColor: "#107c10",
    topicAreas: [
      "Identity & Access Management",
      "Platform Protection",
      "Data & Application Security",
      "Security Operations",
      "Microsoft Defender for Cloud",
      "Azure Sentinel (SIEM)",
    ],
  },
  {
    id: "az-305",
    code: "AZ-305",
    name: "Azure Solutions Architect",
    description: "Validate your expertise in designing cloud and hybrid solutions. The most advanced Azure architect certification.",
    level: "Expert",
    iconColor: "#5c2d91",
    topicAreas: [
      "Identity & Access",
      "Data Storage",
      "Business Continuity",
      "Infrastructure Design",
      "Migration Strategies",
      "Networking Solutions",
      "Application Architecture",
    ],
  },
  {
    id: "az-400",
    code: "AZ-400",
    name: "Azure DevOps Engineer",
    description: "Prove your skills in combining people, processes, and technologies to deliver valuable products and services.",
    level: "Specialty",
    iconColor: "#e3008c",
    topicAreas: [
      "DevOps Transformation",
      "CI/CD Pipelines",
      "Source Control",
      "Infrastructure as Code",
      "Dependency Management",
      "Continuous Testing",
      "Security & Compliance",
    ],
  },
  {
    id: "az-700",
    code: "AZ-700",
    name: "Azure Network Engineer",
    description: "Design and implement Azure networking solutions including hybrid networking, routing, and network security.",
    level: "Specialty",
    iconColor: "#e3008c",
    topicAreas: [
      "Hybrid Networking",
      "Azure Virtual Networks",
      "Routing & Load Balancing",
      "Network Security",
      "Private Access to Services",
      "Azure DNS",
      "ExpressRoute & VPN",
    ],
  },
  {
    id: "dp-203",
    code: "DP-203",
    name: "Azure Data Engineering",
    description: "Demonstrate expertise in integrating, transforming, and consolidating data from various structured and unstructured systems.",
    level: "Specialty",
    iconColor: "#e3008c",
    topicAreas: [
      "Data Storage Design",
      "Data Processing",
      "Data Security",
      "Data Pipelines",
      "Azure Synapse Analytics",
      "Azure Databricks",
      "Stream Processing",
    ],
  },
  {
    id: "ai-102",
    code: "AI-102",
    name: "Azure AI Engineer",
    description: "Design and implement Azure AI solutions using Cognitive Services, Machine Learning, and knowledge mining.",
    level: "Specialty",
    iconColor: "#e3008c",
    topicAreas: [
      "Azure AI Services",
      "Computer Vision",
      "Natural Language Processing",
      "Knowledge Mining",
      "Conversational AI",
      "Azure OpenAI",
      "Responsible AI",
    ],
  },
];

router.get("/exams/certifications", (_req, res) => {
  res.json(CERTIFICATIONS);
});

export default router;
export { CERTIFICATIONS };
